// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnhgrondudzfmshmvmca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaGdyb25kdWR6Zm1zaG12bWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTA1NTksImV4cCI6MjA3MjA2NjU1OX0.m0l6mAPHkwxXAl6E11nmVdWmw0NLf8ofE_D8Oz1KFGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});